### PR TITLE
clone jpa tests into jpa-tck folder Restore the jpa-platform test usage of the ServiceEETest class + prepare for generating new EE TCK tests

### PR DESCRIPTION
**Pull request by scottmarlow**
https://github.com/jakartaee/platform-tck/issues/1418

`jpa-tck` folder is the Standalone Persistence TCK tests and the `jpa` folder will be the Platform TCK Persistence tests.

CC @lukasj 

Locally, after this is merged, I will switch to using latest https://github.com/eclipse-ee4j/jakartaee-tck-tools snapshot build.

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @OndroMih @dmatej
@starksm64 @scottmarlow

### CODE REVIEW

**Comment by scottmarlow** [comment]
I'll try to recreate build failure locally by running with a new local maven repo.

**Comment by scottmarlow** [comment]
Just pushed an update to resolve a merge conflict

**Review by lukasj — APPROVED** [review]
* consider adding some readme saying which tck it actually is into each folder
* consider add `-SNAPSHOT` to the platform version to denote work in progress 

it's a pity that one cannot copy&paste just a subset of tests which are relevant for the platform (https://github.com/jakartaee/jakarta.ee/issues/1813)

**Comment by scottmarlow** [comment]
> * consider adding some readme saying which tck it actually is into each folder
> 
>     * consider add `-SNAPSHOT` to the platform version to denote work in progress

Should already be 11.0.0-SNAPSHOT unless we missed updating a pom.xml, will check
> 
> 
> it's a pity that one cannot copy&paste just a subset of tests which are relevant for the platform ([jakartaee/jakarta.ee#1813](https://github.com/jakartaee/jakarta.ee/issues/1813))

One idea was to update the already balloted Persistence 3.2 https://github.com/scottmarlow/jakartaee-tck/blob/jpa_jpa-tck_prepareformerge/jpa-tck/common/src/main/java/ee/jakarta/tck/persistence/common/PMClientBase.java to extend  the ServiceEETest class like https://github.com/scottmarlow/jakartaee-tck/blob/jpa_jpa-tck_prepareformerge/jpa/common/src/main/java/ee/jakarta/tck/persistence/common/PMClientBase.java does with logger changes.

Tests would also need logger changes as well which we did make to the `jpa` folder tests and some other minor changes.  

jpa/common/src + jpa-tck/common/src are exactly the same (no changes made). 
jpa/common/pom.xml does have changes made mostly to add a dependency on the /jpa/pom.xml.

**Pull request merged**
