### PR TITLE
[tckrefactor] Jakarta Persistence 3.2 - EntityManagerFactory runInTransaction(), callInTransaction() and getName() tests

### PR DESCRIPTION
**Pull request by rfelcman**
Another set of tests for new Jakarta Persistence 3.2. In this case it's about EntityManagerFactory new features:
https://jakartaee.github.io/persistence/latest-nightly/nightly.html#jakarta-persistence-3-2

- Added  EntityManagerFactory runInTransaction(), callInTransaction() and getName() tests

plus fix in PMClientBase.java to generate persistence.xml content in valid with XML Schema (elements order)

CC @lukasj @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @OndroMih @dmatej
@starksm64 @scottmarlow

### CODE REVIEW

**Review by lukasj — APPROVED** [review]
I'd really try to avoid tabs - at least in new files

**Comment by rfelcman** [comment]
> I'd really try to avoid tabs - at least in new files

Sorry, I'll keep it in mind. It seems, that tabs are default formatting for current TCK files.

**Comment by lukasj** [comment]
> It seems, that tabs are default formatting for current TCK files.

There was some discussion that spaces should be used instead - but that may have been related to pom files only

**Review by gurunrao — APPROVED** [review]

**Comment by scottmarlow** [comment]
As per the following searches for tabs in java + xml files, we have around 342745 lines that contain tab characters:
> grep -Pr '\t' --include=*.java|wc -l
> 200962
> jakarta/platformtck $ grep -Pr '\t' --include=*.xml|wc -l
> 141783

I prefer spaces also but it would be difficult to review any pull request that tries to replace tabs with spaces in existing files.  Although it is easy to ignore white space via `git diff -w`.  This pull request is merged and tab vs spaces discussion is like comparing emacs vs vi (or intellij vs eclipse or many other editors, I used to like the brief editor :). 

Thank you for your contributions @rfelcman!  Very much appreciated

**Comment by lukasj** [comment]
> I prefer spaces also but it would be difficult to review any pull request that tries to replace tabs with spaces in existing files.

I agree. It's the sort of thing to do early in the release cycle, since there can be places where the tab (or any other obscure formatting) is appropriate. In some projects I've just changed it and put related commits into [.git-blame-ignore-revs](https://github.com/jakartaee/mail-api/blob/master/.git-blame-ignore-revs) to keep the history clean

**Pull request merged**
