### PR TITLE
Remove servlet TCK code as this has been moved to servlet spec repository

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

**Fixes Issue**
TCK code moved to servlet repo via this PR https://github.com/jakartaee/servlet/pull/540

**Related Issue(s)**
Specify any related issue(s) links.

**Describe the change**
A clear and concise description of the change.

**Additional context**

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @OndroMih @dmatej
@starksm64 @scottmarlow

### CODE REVIEW

**Review by scottmarlow — APPROVED** [review]

**Comment by scottmarlow** [comment]
@olamy I am very thrilled to see the progress via https://github.com/jakartaee/servlet/pull/540 is merged, well done!

**Comment by olamy** [comment]
@scottmarlow yup finally :) 
we should discuss about removing servlet tck from `master` here as well.
not sure what could be the timeline.
probably better in mailing list.

**Comment by scottmarlow** [comment]
> @scottmarlow yup finally :) we should discuss about removing servlet tck from `master` here as well. not sure what could be the timeline. probably better in mailing list.

:+1:

**Comment by scottmarlow** [comment]
https://github.com/jakartaee/platform-tck/issues/1180 mentions ` Servlets with EJB, like the com/sun/ts/tests/servlet/ee/spec/security/runA`.   

https://github.com/jakartaee/platform-tck/pull/1200 deletes more of the ee test source I think. 

Should we restore any of the EE tests that were already previously deleted?  I think via commits e053c03a5fd8a066f5a6ec0cd54eec2f5e9e87a8 + b7c8eded0f2f90b1dc3079f8a051658c24504228

**Comment by scottmarlow** [comment]
> #1180 mentions ` Servlets with EJB, like the com/sun/ts/tests/servlet/ee/spec/security/runA`.
> 
> #1200 deletes more of the ee test source I think.
> 
> Should we restore any of the EE tests that were already previously deleted? I think via commits [e053c03](https://github.com/jakartaee/platform-tck/commit/e053c03a5fd8a066f5a6ec0cd54eec2f5e9e87a8) + [b7c8ede](https://github.com/jakartaee/platform-tck/commit/b7c8eded0f2f90b1dc3079f8a051658c24504228)

I think the work to do is figuring out if we need the ^ mentioned EE tests and also figure out a way to run the Servlet TCK tests as part of the Platform TCK or to require the Servlet TCK to be run instead of that is enough (since it supports EE test deployment).

**Review by gurunrao — APPROVED** [review]
thanks @olamy

**Review by gurunrao — CHANGES_REQUESTED** [review]
ee tests should not be removed

**Comment by scottmarlow** [comment]
I do not see tests/servlet tests mentioned in EE 10 vehicle properties so think this change is fine (pending correction of conflicts).

**Comment by gurunrao** [comment]
> I do not see tests/servlet tests mentioned in EE 10 vehicle properties so think this change is fine (pending correction of conflicts).

https://github.com/jakartaee/platform-tck/tree/main/servlet/src/main/java/com/sun/ts/tests/servlet/ee/platform/cdi - beans.xml can be removed?

**Comment by scottmarlow** [comment]
> > I do not see tests/servlet tests mentioned in EE 10 vehicle properties so think this change is fine (pending correction of conflicts).
> 
> https://github.com/jakartaee/platform-tck/tree/main/servlet/src/main/java/com/sun/ts/tests/servlet/ee/platform/cdi - beans.xml can be removed?

Instead of removing anything just yet, I think we need to understand how to validate that EE 11 implementations can pass the Servlet tests that are now in the Servlet 6.2 Spec TCK.

**Comment by scottmarlow** [comment]
I ran the same EE 10 tests and the jakartaeetck/dist/com/sun/ts/tests/ejb32/lite/timer/basic/xa/ejb32_lite_timer_basic_xa_ejblitejsf_vehicle_web.war WEB-INF/classes/META-INF/persistence.xml file contains:

```
<!--

    Copyright (c) 2018, 2021 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

-->

<persistence xmlns="https://jakarta.ee/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence
    https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd"
             version="3.0">
    <persistence-unit name="ejblite-pu" transaction-type="JTA">
        <jta-data-source>jdbc/DBTimer</jta-data-source>
    </persistence-unit>
</persistence>
```

**Comment by arjantijms** [comment]
The servlet tests have now been removed from the platform TCK.

**Pull request closed without merging**
