### PR TITLE
Optional elresolver updates

### PR DESCRIPTION
**Pull request by markt-asf**
**Fixes Issue**
No issue. The EL spec has been updated. One change and some additional tests are required.

**Related Issue(s)**
None.

**Describe the change**
Updates the existing OptionalELResolver tests for property resolution.
Adds new OptionalELResolver tests for method invocation.
Cleans up the code for the OptionalELResolver tests.

**Additional context**
None.

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @OndroMih @dmatej
@starksm64 @scottmarlow

### CODE REVIEW

**Comment by alwin-joseph** [comment]
Will verify when new API jar is released after https://github.com/jakartaee/expression-language/pull/208 is merged.

**Comment by markt-asf** [comment]
Tx. 6.0.0-RC1  has been published that includes that change.

**Comment by alwin-joseph** [comment]
I encountered 1 test failure , using GlassfishM2 (and copying el api 6.0.0-RC1 jar). Other new tests passed.

Errors: 
[ERROR]   ELClientIT.optionalELResolverObjectInvoke:227->testOptionalELResolverInvoke:270
[ERROR] Tests run: 361, Failures: 0, Errors: 1, Skipped: 0
```
java.lang.NullPointerException: Cannot read the array length because "<local7>" is null
        at com.sun.ts.tests.el.api.jakarta_el.optionalelresolver.ELClientIT.testOptionalELResolverInvoke(ELClientIT.java:270)
        at com.sun.ts.tests.el.api.jakarta_el.optionalelresolver.ELClientIT.optionalELResolverObjectInvoke(ELClientIT.java:227)
```

**Comment by markt-asf** [comment]
A fix will be required in Glassfish (ExpressLy?) for that. The expected behaviour has changed.

**Comment by alwin-joseph** [comment]
> A fix will be required in Glassfish (ExpressLy?) for that. The expected behaviour has changed.

Okey. I will merge this and update the bundle at https://www.eclipse.org/downloads/download.php?file=/ee4j/jakartaee-tck/jakartaee11/staged/eftl/jakarta-expression-language-tck-6.0.0.zip. Will retest when expressly has the required changes integrated.

**Review by alwin-joseph — APPROVED** [review]

**Comment by arjantijms** [comment]
> A fix will be required in Glassfish (ExpressLy?) for that. The expected behaviour has changed.

I'll take a look at that soon (should be in M3 then). Thanks!

**Comment by arjantijms** [comment]
> A fix will be required in Glassfish (ExpressLy?) for that. The expected behaviour has changed.

As it appeared this issue was entirely in the API jar. I do wonder how Tomcat was able to pass this, unless a different API jar was used.

**Comment by markt-asf** [comment]
Tomcat has always provided its own API JARs for all the specs it implements.

**Comment by arjantijms** [comment]
> Tomcat has always provided its own API JARs for all the specs it implements.

Thanks, that clears it up.

**Pull request merged**
