### PR TITLE
JPA#391 Fix wrongly typed comparison expressions

### PR DESCRIPTION
**Pull request by beikov**
**Fixes Issue**
https://github.com/jakartaee/persistence/issues/391

**Describe the change**
Fix queries which were wrongly comparing expressions of incompatible types.

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @OndroMih @dmatej
@starksm64 @scottmarlow

### CODE REVIEW

**Review by dmatej — COMMENTED** [review]
Seems I am forgetting, I had to open specs to check if this syntax is really needed. And it is. However ... shouldn't be the `Collection<Date>` changed to `Collection<LocalDate>`? And the same for `Timestamp tsValue` to `LocalDateTime`.

**Comment by beikov** [comment]
I don't necessarily care about modernization in the TCK, but IMO the correctness aspect should be fixed. You can create a separate PR if you want to update the types in the models, though I think it might be worth having some tests around that still make use of the old `java.sql` temporal types.

**Comment by dmatej** [comment]
Yeah, I see, we would have to change also `private Date hireDate;`
Ok.

**Review by dmatej — APPROVED** [review]

**Comment by scottmarlow** [comment]
@lukasj pending the https://github.com/jakartaee/persistence/issues/391 being labeled as `challenge` and `approved`, do you have a preference for whether this test change is back ported for `EE Platform TCK 10`/`Persistence 3.1 TCK` or excluded?

**Comment by scottmarlow** [comment]
> @lukasj pending the [jakartaee/persistence#391](https://github.com/jakartaee/persistence/issues/391) being labeled as `challenge` and `approved`, do you have a preference for whether this test change is back ported for `EE Platform TCK 10`/`Persistence 3.1 TCK` or excluded?

Never mind, I already asked this before and the answer was to exclude the tests.  I did the same via https://github.com/jakartaee/platform-tck/pull/1158

**Pull request merged**
