### PR TITLE
 JSTL TCK Refactoring using Arquillian and JUnit

### PR DESCRIPTION
**Pull request by alwin-joseph**
**Related Issue(s)**
https://github.com/jakartaee/platform-tck/issues/1126

**Describe the change**
- Converted standalone legacy JSTL Tests under jstl/src/main/java/com/sun/ts/tests/jstl/ to run as Junit tests, uses Arquillian
- Created glassfish runner at glassfish-runner/jstl-tck, tests pass with Glassfish 7 
- No vehicle specified in https://github.com/jakartaee/platform-tck/blob/e3ab547f4308877e2178ef21609c0d8aac45f766/install/jakartaee/other/vehicle.properties, hence standalone and platform run implementations are same.

Pending items : 
- 1 signature test is pending to be refactored , will be covered in separate PR
- Address test failures with Glassfish8

### CODE REVIEW

**Comment by gurunrao** [comment]
@scottmarlow @alwin-joseph - IMO, we should continue with review and merge of the PR, since same changes will be helpful for Platform TCK EE 11 release.

**Comment by gurunrao** [comment]
@alwin-joseph - Please test with latest GF 8 version + JDK21.

**Comment by alwin-joseph** [comment]
> @alwin-joseph - Please test with latest GF 8 version + JDK21.

My analysis: 

Total tests : 538
- All tests pass with GF7 + JDK11
- 67 test failures with GF8-M1 + JDK17
- 82 test failures with GF8-M2 + JDK21

I suggest the test failures be addressed in separate change if possible. https://github.com/jakartaee/tags/issues/255 reports several JDK related issues for Tags TCK. Those fixes can be applied to the refactored source.

**Comment by scottmarlow** [comment]
> > @alwin-joseph - Please test with latest GF 8 version + JDK21.
> 
> My analysis:
> 
> Total tests : 538
> 
>     * All tests pass with GF7 + JDK11
> 
>     * 67 test failures with GF8-M1 + JDK17
> 
>     * 82 test failures with GF8-M2 + JDK21
> 
> 
> I suggest the test failures be addressed in separate change if possible. [jakartaee/tags#255](https://github.com/jakartaee/tags/issues/255) reports several JDK related issues for Tags TCK. Those fixes can be applied to the refactored source.

I like that  this pull request kept the same TCK test package name as it was with EE 10.  I meant to mention that it is harder to automate the refactoring when we change the test class or package names (we can hack around that with package mapping but that will be kind of tedious).  

Not related to this pr but the latest automation changes are in:

https://github.com/scottmarlow/jakartaee-tck/tree/rewritejpahttps://github.com/scottmarlow/jakartaee-tck-tools/tree/rewritejpa tck-rewrite folder + jar2shrinkwrap folder.

https://github.com/scottmarlow/jakartaee-tck/tree/rewritejpa doesn't have the output of the ^ changes but I can probably push a sample of those changes to a different branch.

**Comment by gurunrao** [comment]
> > @alwin-joseph - Please test with latest GF 8 version + JDK21.
> 
> My analysis:
> 
> Total tests : 538
> 
>     * All tests pass with GF7 + JDK11
> 
>     * 67 test failures with GF8-M1 + JDK17
> 
>     * 82 test failures with GF8-M2 + JDK21
> 
> 
> I suggest the test failures be addressed in separate change if possible. [jakartaee/tags#255](https://github.com/jakartaee/tags/issues/255) reports several JDK related issues for Tags TCK. Those fixes can be applied to the refactored source.

82 failures are more than expected when compared to challenges for JDK failures at https://github.com/jakartaee/tags/issues/255 and https://github.com/jakartaee/tags/issues/256. It will be great if we can identify and notify glassfish team on the failures which are not part of challenges, so that we know the root cause of the failures.

**Comment by alwin-joseph** [comment]
> 
> 82 failures are more than expected when compared to challenges for JDK failures at [jakartaee/tags#255](https://github.com/jakartaee/tags/issues/255) and [jakartaee/tags#256](https://github.com/jakartaee/tags/issues/256). It will be great if we can identify and notify glassfish team on the failures which are not part of challenges, so that we know the root cause of the failures.

Agree. Hopefully those can be tracked on a separate issue.

**Review by gurunrao — APPROVED** [review]
LGTM, Thanks for PR @alwin-joseph. Please create a tracking issue for GF 8 failures, which are not part of challenges open/accepted.

**Pull request merged**
