### PR TITLE
prepare for 11.0.0-M1 release of signaturetest, runtime, libutil, common

### PR DESCRIPTION
**Pull request by scottmarlow**

### CODE REVIEW

**Review by gurunrao — APPROVED** [review]
LGTM

**Comment by gurunrao** [comment]
Build is failing due to dependency on signaturetest, runtime, libutil, common libraries SNAPSHOT version in other modules like assembly. IMO for build to succeed, we should search and replace all dependencies to M1.

**Comment by olamy** [comment]
usually in the Maven world poms should have non SNAPSHOT versions only temporarily. just the time to commit, tag then commit to next SNAPSHOT.
I don't think it's a good idea to commit such change in the main branch. Users who get this revision locally may have wrong version 11.0.0-M1 locally.

Should be in a release branch, not the main working one.

**Comment by scottmarlow** [comment]
> Build is failing due to dependency on signaturetest, runtime, libutil, common libraries SNAPSHOT version in other modules like assembly. IMO for build to succeed, we should search and replace all dependencies to M1.

+1 thanks @gurunrao 

> usually in the Maven world poms should have non SNAPSHOT versions only temporarily. just the time to commit, tag then commit to next SNAPSHOT.
I don't think it's a good idea to commit such change in the main branch. Users who get this revision locally may have wrong version 11.0.0-M1 locally.
>
> Should be in a release branch, not the main working one.

@olamy should we create a `11.0.0-M1` branch for the release?

**Comment by scottmarlow** [comment]
I pushed the release branch to https://github.com/jakartaee/platform-tck/tree/11.0.0-M1

**Comment by olamy** [comment]
sorry for late reply but yes using a release branch is perfect

**Pull request closed without merging**
