### PR TITLE
[Issue1176] Do not add SecTest interface to war package file

### PR DESCRIPTION
**Pull request by PatrickHuang888**
**Fixes Issue**
Specify the issue (link) that is solved with this pull request.
https://github.com/jakartaee/platform-tck/issues/1176
**Related Issue(s)**
Specify any related issue(s) links.

**Describe the change**
do not add SecTest interface to war file package

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @OndroMih @dmatej
@starksm64 @scottmarlow

actullly I had this issue on 8.0.2, not verified on master branch, I have only 1 file to midification, but it seems I cannot pull request on 8? I think it should be a issue on master either?
Thanks
Patrick

### CODE REVIEW

**Comment by olamy** [comment]
No it's not. I was not sure how to migrate this as it's related to EJB and nothing really servlet container only (If I understand correctly?)
Sorry I forgot to ask. But maybe if related to EJB this should be in ejb tck?

**Comment by scottmarlow** [comment]
> No it's not. I was not sure how to migrate this as it's related to EJB and nothing really servlet container only (If I understand correctly?) Sorry I forgot to ask. But maybe if related to EJB this should be in ejb tck?

I'll start a Platform TCK issue for creating Servlet tests that work with EJBs such as the `com/sun/ts/tests/servlet/ee/spec/security/runAs` tests.

**Comment by scottmarlow** [comment]
> No it's not. I was not sure how to migrate this as it's related to EJB and nothing really servlet container only (If I understand correctly?) Sorry I forgot to ask. But maybe if related to EJB this should be in ejb tck?

@olamy thanks for the answer.  No need to apologize, I missed these as well when reviewing the Servlet pull request.  I don't expect that the Servlet TCK would test against EJB as that is not expected.

**Comment by gurunrao** [comment]
Please re-open PR as needed....

**Pull request closed without merging**
