### PR TITLE
Address persistence/issues/391 TCK Challenge for Wrong typed comparison expressions in TCK

### PR DESCRIPTION
**Pull request by scottmarlow**
**Fixes Issue**
https://github.com/jakartaee/persistence/issues/391

**Describe the change**

Prepare to exclude the challenged Persistence TCK tests:

> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest27_from_standalone
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest29_from_standalone
> com/sun/ts/tests/jpa/se/entityManager/Client.java#typedQueryMethodsAfterClose16Test_from_standalone

Prepare to exclude the challenged Platform TCK tests:
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest27_from_appmanagedNoTx
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest27_from_pmservlet
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest27_from_puservlet
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest27_from_stateless3
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest29_from_appmanagedNoTx
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest29_from_pmservlet
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest29_from_puservlet
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest29_from_stateless3

CC @alwin-joseph @anajosep @arjantijms @cesarhernandezgt @dblevins @m0mus @edbratt @gurunrao @jansupol @jgallimore @kazumura @kwsutter @LanceAndersen @bhatpmk @RohitKumarJain @shighbar @gthoman @brideck @OndroMih @dmatej
@starksm64 @scottmarlow

### CODE REVIEW

**Comment by dmatej** [comment]
Do we really need to exclude these tests? I understood they should be improved, because they are not correct despite they do pass. @beikov , what do you think?

**Comment by scottmarlow** [comment]
> Do we really need to exclude these tests? 

We could update the challenged tests as per updated [TCK Process](https://jakarta.ee/committees/specification/tckprocess/):

> As another alternative to excluding a challenged test, it may be possible to adjust the test validation logic to “expand” the validation check. E.g. if a test expects a value “A1” for a specific variable “x”, but a challenge is raised arguing that the specification language actually allows for either values “A1” and “A2” (but no other values) to be valid values for “x”, then it could be a valid course of action to modify the challenged test to allow either “A1” OR “A2” for “x”.
> 
> Since this line of thinking might be applied to cases that aren’t quite as straightforward as this example, care should be taken when using this approach. A particular danger is that an implementation that has already demonstrated compliance before the challenge was raised might actually not pass the new, modified test.
> 
> To limit the confusion and additional work such a scenario would cause, if there is already at least one certified compatible implementation before the challenge, the new, modified TCK should be run against at least one such implementation (and ideally all of them) before the changes are published, released, and finalized.
> 
> If such a change were released, and it was later found to cause a previously-certified implementation to fail the new, modified test, then excluding the test would likely be the only option, and this would require yet another, additional service release.

@lukasj do you have feedback on whether we exclude or update the src/com/sun/ts/tests/jpa/core/query/apitests/Client#queryAPITest27, src/com/sun/ts/tests/jpa/core/query/apitests/Client#queryAPITest29 and src/com/sun/ts/tests/jpa/se/entityManager/Client#typedQueryMethodsAfterClose16Test tests?  It is harder to update the tests as there could be future challenges asking that we instead exclude the tests because of another Persistence Provider implementation depending on the previous behavior (outcome of the future challenge should be to then exclude the tests IMO).

If we instead updated the challenged tests, we could back port the https://github.com/jakartaee/platform-tck/pull/1157 change to the `10.0.x` branch.

**Comment by lukasj** [comment]
I vote for simple removals/exclusions in older releases

**Comment by scottmarlow** [comment]
> I vote for simple removals/exclusions in older releases

I'm going to proceed with releasing the Platform + Persistence TCKs since I at least have input from Lukas that his vote is to exclude challenged tests in older releases. If anyone objects and wants to start a discussion on the Persistence SPEC mailing list to counter that, that is also fine and expected as a possibility. The mail subject would be to request that all Persistence SPEC committers vote on whether the test is updated or excluded for the 3.1 release (with a time line for the voting of 2 weeks).

You will see me going through the steps of processing this TCK challenge but if we have an (Persistence Spec committer team) ballot outcome in 2 weeks that the test should be changed, we can then release the TCKs again with the test change and this pr reverted.

**Comment by scottmarlow** [comment]
I verified that testing http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl//jakarta-persistence-tck-3.1.2.zip with GlasFish/EclipseLink shows that the challenged tests are not run:

> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest27_from_standalone
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest29_from_standalone
> com/sun/ts/tests/jpa/se/entityManager/Client.java#typedQueryMethodsAfterClose16Test_from_standalone

Next we will build/stage the Platform TCK to verify that the following tests are excluded:
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest27_from_appmanagedNoTx
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest27_from_pmservlet
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest27_from_puservlet
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest27_from_stateless3
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest29_from_appmanagedNoTx
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest29_from_pmservlet
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest29_from_puservlet
> com/sun/ts/tests/jpa/core/query/apitests/Client.java#queryAPITest29_from_stateless3

**Pull request merged**
