### PR TITLE
Glassfish runner for ejb32 module

### PR DESCRIPTION
**Pull request by alwin-joseph**
**Related Issue(s)**
https://github.com/jakartaee/platform-tck/issues/1421
https://github.com/jakartaee/platform-tck/issues/1434

**Describe the change**
- Create glassfish runner for ejb32 module
- Latest test result with GF-JDK17-M7:
Javatests: Tests run: 682, Failures: 0, Errors: 0, Skipped: 0
Appclient Tests : Tests run: 22, Failures: 0, Errors: 22, Skipped: 0

**Additional context**
Jenkins Job : https://ci.eclipse.org/jakartaee-tck/job/11/job/platform-tck/job/ejb32-platform-tck-run 

cc @arjantijms 

@starksm64 I see 121 ejbembed vehicle tests are not present in the refactored source, compared to EE10 TCK, is that expected ?

### CODE REVIEW

**Comment by arjantijms** [comment]
@alwin-joseph Just wondering, what is the difference with this one: https://github.com/jakartaee/platform-tck/blob/main/glassfish-runner/enterprise-beans-tck/enterprise-beans-tck-run/pom.xml ?

That one also runs the ejb32 tests.

**Comment by alwin-joseph** [comment]
> @alwin-joseph Just wondering, what is the difference with this one: https://github.com/jakartaee/platform-tck/blob/main/glassfish-runner/enterprise-beans-tck/enterprise-beans-tck-run/pom.xml ?
> 
> That one also runs the ejb32 tests.

Somehow I assumed that this only covered ejb30 tests after yesterday's discussion !! Are the results better than this one? I can close this as this is duplicating the same.  

cc @edburns @starksm64

**Comment by arjantijms** [comment]
> Somehow I assumed that "glassfish-runner/enterprise-beans-tck" only covered ejb30 tests after yesterday's discussion !! 

EJB should be just one spec (although we do need a profile for the lite subset). Somehow the old TCK put ejb30 and ejb32 into two separate folders, but they still belong together of course. Within the EJB TCK (and hence the folder enterprise-beans-tck) we can still execute 30 and 32 separately, or even make some more subsets.

> Are the results better than this runner ? I can close this as this is duplicating the same.

For EJB32 I had them all passing indeed, so should be a little better.

**Comment by alwin-joseph** [comment]
> > Somehow I assumed that "glassfish-runner/enterprise-beans-tck" only covered ejb30 tests after yesterday's discussion !!
> 
> EJB should be just one spec (although we do need a profile for the lite subset). Somehow the old TCK put ejb30 and ejb32 into two separate folders, but they still belong together of course. Within the EJB TCK (and hence the folder enterprise-beans-tck) we can still execute 30 and 32 separately, or even make some more subsets.

Ok got it. 
> 
> > Are the results better than this runner ? I can close this as this is duplicating the same.
> 
> For EJB32 I had them all passing indeed, so should be a little better.

Thats good! I'll close this one then.

**Comment by scottmarlow** [comment]
Should the ear based ejb tests also be run by enterprise-beans-tck?  I ran last night just to see the generated (ear) deployments under the targer folder and I only saw the war deployments.  Not sure if that is a problem or not (perhaps I was just missing some changes).

**Comment by alwin-joseph** [comment]
> Should the ear based ejb tests also be run by enterprise-beans-tck? I ran last night just to see the generated (ear) deployments under the targer folder and I only saw the war deployments. Not sure if that is a problem or not (perhaps I was just missing some changes).

The runner currently selects the javatests (jsp, servlet vehicles) https://github.com/jakartaee/platform-tck/blob/b2d85f5577152cbf8d97afd3054e477f9e0a2977/glassfish-runner/enterprise-beans-tck/enterprise-beans-tck-run/pom.xml#L312 .

There are 22 appclient tests in ejb32

**Comment by scottmarlow** [comment]
On Mon, Oct 21, 2024, 4:37 AM Alwin Joseph ***@***.***> wrote:

> Should the ear based ejb tests also be run by enterprise-beans-tck? I ran
> last night just to see the generated (ear) deployments under the targer
> folder and I only saw the war deployments. Not sure if that is a problem or
> not (perhaps I was just missing some changes).
>
> The runner currently selects the javatests (jsp, servlet vehicles)
> https://github.com/jakartaee/platform-tck/blob/b2d85f5577152cbf8d97afd3054e477f9e0a2977/glassfish-runner/enterprise-beans-tck/enterprise-beans-tck-run/pom.xml#L312
> .
>
> There are 22 appclient tests in ejb32
>

I didn't see any app client tests run when I local ran.  What is the
command line to use that includes app client tests?

**Comment by alwin-joseph** [comment]
> Should the ear based ejb tests also be run by enterprise-beans-tck? I ran last night just to see the generated (ear) deployments under the targer folder and I only saw the war deployments. Not sure if that is a problem or not (perhaps I was just missing some changes). The runner currently selects the javatests (jsp, servlet vehicles) https://github.com/jakartaee/platform-tck/blob/b2d85f5577152cbf8d97afd3054e477f9e0a2977/glassfish-runner/enterprise-beans-tck/enterprise-beans-tck-run/pom.xml#L312 . There are 22 appclient tests in ejb32
> I didn't see any app client tests run when I local ran. What is the command line to use that includes app client tests?

To run those tests more changes would need to be made in the pom.xml, I believe they are WIP. A new execution for the test group `tck-appclient` would be needed like in https://github.com/jakartaee/platform-tck/blob/b2d85f5577152cbf8d97afd3054e477f9e0a2977/glassfish-runner/enterprise-beans-tck/enterprise-beans-tck-run/pom.xml#L312 (using appclient-arquillian.xml),  and use `mvn clean verify` to run those 22 tests. When I ran them last week using this closed PR, they were not passing and looks like some test changes may be needed to pass them. 

If you are looking to run appclient/ejb tests there are other modules as eg: JMS (https://github.com/jakartaee/platform-tck/pull/1605).

**Comment by scottmarlow** [comment]
@alwin-joseph I just need one of the  generated ear files that work that includes EJB session beans that are available via JNDI so I can compare that EARs deployment descriptors to one of the JPA EARs like /jpa-platform-tck/target/deployments/tck-appclient_jpa_core_EntityGraph_appmanaged_vehicle_jpa_core_EntityGraph_appmanaged_vehicles.ear

Should we update the JMS CI job to include `**/*.ear` for a test run so I can download the zipped ears?

**Comment by scottmarlow** [comment]
> Should we update the JMS CI job to include `**/*.ear` for a test run so I can download the zipped ears?

I made this change for the https://ci.eclipse.org/jakartaee-tck/job/11/job/platform-tck/job/jms-platform-tck-run/7 run

**Comment by scottmarlow** [comment]
Note that https://ci.eclipse.org/jakartaee-tck/job/11/job/platform-tck/job/jms-platform-tck-run/6/ does have failures even though the test result indicates there were none.  From https://ci.eclipse.org/jakartaee-tck/job/11/job/platform-tck/job/jms-platform-tck-run/6/console:

> 10-21-2024 14:58:21:  ERROR: Caught exception: javax.naming.NamingException: Lookup failed for java:app/AppClientMyTestQueueConnectionFactory in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}] [Root exception is javax.naming.NameNotFoundException: No object bound for java:app/AppClientMyTestQueueConnectionFactory]
> 10-21-2024 14:58:21:  ERROR: Test case throws exception: java.lang.Exception: setup failed!
> 10-21-2024 14:58:21:  ERROR: Exception at:  
> 10-21-2024 14:58:21:  ERROR: java.lang.Exception: setup failed!
> 	at com.sun.ts.tests.jms.ee20.resourcedefs.descriptor.Client.setup(Client.java:182)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at com.sun.ts.lib.harness.EETest.run(EETest.java:575)
> 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:138)
> 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:494)
> 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:232)
> 	at com.sun.ts.lib.harness.EETest.run(EETest.java:296)
> 	at com.sun.ts.tests.jms.ee20.resourcedefs.descriptor.Client.main(Client.java:99)
> Caused by: javax.naming.NamingException: Lookup failed for java:app/AppClientMyTestQueueConnectionFactory in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}] [Root exception is javax.naming.NameNotFoundException: No object bound for java:app/AppClientMyTestQueueConnectionFactory]
> 	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:836)
> 	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:257)
> 	at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
> STATUS:Failed.Test case throws exception: java.lang.Exception: setup failed!
> 	at com.sun.ts.lib.util.TSNamingContext.lookup(TSNamingContext.java:70)
> 	at com.sun.ts.tests.jms.ee20.resourcedefs.descriptor.Client.setup(Client.java:158)
> 	... 10 more
> Caused by: javax.naming.NameNotFoundException: No object bound for java:app/AppClientMyTestQueueConnectionFactory
> 	at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:135)
> 	at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:818)
> 	... 14 more
> 	Suppressed: javax.naming.NameNotFoundException: No object bound to name java:app/AppClientMyTestQueueConnectionFactory in namespace JavaNamespace[name=resourcedefs_descriptor_appclient_vehicle_client, keys=[java:/, java:app/env/, java:app/env, java:app/, java:, java:app]]
> 		at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:617)
> 		at com.sun.enterprise.naming.impl.GlassfishNamingManagerImpl.lookup(GlassfishNamingManagerImpl.java:587)
> 		at com.sun.enterprise.naming.impl.JavaURLContext.lambda$lookup$0(JavaURLContext.java:153)
> 		at com.sun.enterprise.naming.impl.JavaURLContext.lookupOrCollectException(JavaURLContext.java:550)
> 		at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:153)
> 		... 15 more
> 	Suppressed: javax.naming.NamingException: Lookup failed for java:global/resourcedefs_descriptor_appclient_vehicle_client/AppClientMyTestQueueConnectionFactory in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}] [Root exception is javax.naming.NameNotFoundException: resourcedefs_descriptor_appclient_vehicle_client]
> 		at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:836)
> 		at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:257)
> 		at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
> 		at com.sun.enterprise.naming.impl.JavaURLContext.lookupOrCollectException(JavaURLContext.java:550)
> 		at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:171)
> 		... 15 more
> 	Caused by: javax.naming.NameNotFoundException: resourcedefs_descriptor_appclient_vehicle_client
> 		at com.sun.enterprise.naming.impl.TransientContext.resolveContext(TransientContext.java:292)
> 		at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:205)
> 		at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:206)
> 		at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:37)
> 		at com.sun.enterprise.naming.impl.RemoteSerialContextProviderImpl.lookup(RemoteSerialContextProviderImpl.java:85)
> 		at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
> 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 		at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:122)
> 		at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:152)
> 		at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:501)
> 		at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:172)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1529)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:1405)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleInput(MessageMediatorImpl.java:910)
> 		at com.sun.corba.ee.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:192)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:674)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.dispatch(MessageMediatorImpl.java:476)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.doWork(MessageMediatorImpl.java:2202)
> 		at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:476)
> 		at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:519)
> 	Suppressed: javax.naming.NamingException: Lookup failed for __internal_java_app_for_app_client__resourcedefs_descriptor_appclient_vehicle_client__java:app/AppClientMyTestQueueConnectionFactory in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}] [Root exception is javax.naming.NameNotFoundException: __internal_java_app_for_app_client__resourcedefs_descriptor_appclient_vehicle_client__java:app]
> 		at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:836)
> 		at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:257)
> 		at java.naming/javax.naming.InitialContext.lookup(InitialContext.java:409)
> 		at com.sun.enterprise.naming.impl.JavaURLContext.lookupOrCollectException(JavaURLContext.java:550)
> 		at com.sun.enterprise.naming.impl.JavaURLContext.lookup(JavaURLContext.java:178)
> 		... 15 more
> 	Caused by: javax.naming.NameNotFoundException: __internal_java_app_for_app_client__resourcedefs_descriptor_appclient_vehicle_client__java:app
> 		at com.sun.enterprise.naming.impl.TransientContext.resolveContext(TransientContext.java:292)
> 		at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:205)
> 		at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:37)
> 		at com.sun.enterprise.naming.impl.RemoteSerialContextProviderImpl.lookup(RemoteSerialContextProviderImpl.java:85)
> 		at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
> 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 		at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:122)
> 		at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:152)
> 		at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatchToServant(ServerRequestDispatcherImpl.java:501)
> 		at com.sun.corba.ee.impl.protocol.ServerRequestDispatcherImpl.dispatch(ServerRequestDispatcherImpl.java:172)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequestRequest(MessageMediatorImpl.java:1529)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:1405)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleInput(MessageMediatorImpl.java:910)
> 		at com.sun.corba.ee.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:192)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.handleRequest(MessageMediatorImpl.java:674)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.dispatch(MessageMediatorImpl.java:476)
> 		at com.sun.corba.ee.impl.protocol.MessageMediatorImpl.doWork(MessageMediatorImpl.java:2202)
> 		at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:476)
> 		at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:519)
>

**Comment by alwin-joseph** [comment]
> Note that https://ci.eclipse.org/jakartaee-tck/job/11/job/platform-tck/job/jms-platform-tck-run/6/ does have failures even though the test result indicates there were none. From https://ci.eclipse.org/jakartaee-tck/job/11/job/platform-tck/job/jms-platform-tck-run/6/console:
> 
> > 10-21-2024 14:58:21:  ERROR: Caught exception: javax.naming.NamingException: Lookup failed for java:app/AppClientMyTestQueueConnectionFactory in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.url.pkgs=com.sun.enterprise.naming, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl}] [Root exception is javax.naming.NameNotFoundException: No object bound for java:app/AppClientMyTestQueueConnectionFactory]
> > 10-21-2024 14:58:21:  ERROR: Test case throws exception: java.lang.Exception: setup failed!
> > 10-21-2024 14:58:21:  ERROR: Exception at:
> > 10-21-2024 14:58:21:  ERROR: java.lang.Exception: setup failed!

Yes there are around 370 test failures in JMS. 
FYI, I renamed the job, created one each for appclient and javatests. The job https://ci.eclipse.org/jakartaee-tck/job/11/job/platform-tck/job/jms-platform-tck-appclient-run/7/ has the EARs.

**Comment by scottmarlow** [comment]
https://github.com/jakartaee/platform-tck/blob/main/jms/src/main/java/com/sun/ts/tests/jms/core20/jmscontextqueuetests/ClientAppclientTest.java is only of the tests that pass but doesn't look like that contains any EE server components unless I missed them.  I extracted contents of tck-

> appclient_jmscontextqueuetests_appclient_vehicle_jmscontextqueuetests_appclient_vehicle.ear:
> ├── jmscontextqueuetests_appclient_vehicle_client.jar
> └── lib
>     ├── arquillian-core.jar
>     ├── arquillian-junit5.jar
>     ├── arquillian-protocol-lib.jar
>     ├── arquillian-testenricher-cdi-jakarta.jar
>     ├── arquillian-testenricher-ejb-jakarta.jar
>     ├── arquillian-testenricher-initialcontext.jar
>     └── arquillian-testenricher-resource-jakarta.jar

**Pull request closed without merging**
