### PR TITLE
Fix Maven build of tckrefactor branch

### PR DESCRIPTION
**Pull request by olamy**
- Updates tests from throws Fault to Throws Exception.
- Rename files. (move from src/test to src/main)
- Correct dependencies, remove maven-enforcer-plugin in Maven poms.
- add necessary jaxws:wsgen/jaxws:wsimport
- comment some modules specific to glassfish (glassfishtck, internal, webservices12 and webservices13)

### CODE REVIEW

**Comment by scottmarlow** [comment]
Since the size of this commit is around 251733 lines long, I think we should summarize the general changes included.  Here is my take on it:

1. Updates tests from `throws Fault` to `Throws Exception`.
2. Rename files.
3. Correct dependencies, remove maven-enforcer-plugin in Maven poms.

**Comment by olamy** [comment]
- add necessary jaxws:wsgen/jaxws:wsimport
- comment some modules specific to glassfish (glassfishtck, internal, webservices12 and webservices13)

**Comment by olamy** [comment]
@scottmarlow can we merge this one? I'd really to move forward then with https://github.com/jakartaee/platform-tck/pull/912 and then jsp websocket ....
thanks

**Comment by scottmarlow** [comment]
Thanks for the change @olamy!

**Comment by olamy** [comment]
> Thanks for the change @olamy!

yeah!! thanks for merging!

**Pull request merged**
