### PR TITLE
sync persistence challenges/fixes from master branch

### PR DESCRIPTION
**Pull request by gurunrao**
sync persistence challenges/fixes from master branch

### CODE REVIEW

**Comment by gurunrao** [comment]
@beikov - Please review.

**Comment by beikov** [comment]
Sorry, but I have no idea what the current state of the Persistence TCK is, so I don't know whether these excludes are ok or not.

**Review by lukasj — APPROVED** [review]
consider updating the text in the TCK-Exclude-List.txt file, currently it says (on line 17) _This file lists the excluded tests from Jakarta EL TCK._ - that does not look correct

**Comment by gurunrao** [comment]
> consider updating the text in the TCK-Exclude-List.txt file, currently it says (on line 17) _This file lists the excluded tests from Jakarta EL TCK._ - that does not look correct

Thanks, was copy and base error.

**Comment by scottmarlow** [comment]
> Sorry, but I have no idea what the current state of the Persistence TCK is, so I don't know whether these excludes are ok or not.

Some guidance on excludes from https://jakarta.ee/committees/specification/tckprocess:
> Excludes
>
> Excludes MUST be included in the TCK project release in a format that is compatible with the testing framework in use so that as the excludes are updated, the affected tests are automatically removed from the test suite.
> 
> Adding excluded tests
> Excluded tests should be added back in for every major Jakarta EE release by emptying the test exclude list for every Specification developed in the respective major EE release.

Should we empty all of the TCK excludes list for minor specification updates in EE 11?  Or should that only be done for a major Persistence specification release?

I think that the underlying message behind emptying the exclude list is to give the relevant specification team a chance to rewrite the excluded tests to make them portable or solve whatever problem caused them to be excluded.  I don't think we have process setup currently to deal with this effectively.

**Pull request merged**
